service: starterpack-laravel-base

provider:
  name: aws
  region: us-east-1
  runtime: provided.al2
  environment:
    APP_ENV: production
    APP_DEBUG: true # set to false when moving to production
    APP_KEY: 'base64:/EStlF5sExBpWdQ3eB/h+F2zzKGDc5bvDzwe0KD8ZPg='
  # Enable new serverless.yml features to avoid deprecation warnings
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221

package:
  exclude:
    - node_modules/**
    - public/storage
    - storage/**
    - tests/**
    - .env

plugins:
  - ./vendor/bref/bref

functions:

  api:
    handler: public/index.php
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-81-fpm}
    events:
      - httpApi: '*'

  # Run artisan commands on Lambda by running:
  #     vendor/bin/bref cli starterpack-laravel-base-dev-artisan -- <command>
  artisan:
    handler: artisan
    timeout: 120 # in seconds
    layers:
      - ${bref:layer.php-81} # PHP
      - ${bref:layer.console} # The "console" layer
